<?php

declare(strict_types=1);

$storeId = '$storeId';
$userId = '$userId';
$storeId = 1;
$userId = 2; // 'john.store'

return [
    // Entity Metadata
    'entity' => [
        'name'          => 'Testy',
        'table'         => 'testy',
        'timestamps'    => false,
        'seeder_count'  => 5,
    ],

    // Field Definitions
    'fields' => [
        'id' => [
            'db_type'   => 'bigIncrements',
            'primary'   => true,
            'auto_increment' => true,
            'comment'   => 'ID',
        ],
        'store_id'      => [
            'db_type' => 'foreignId',
            'nullable' => true,
            'comment' => 'Store this record belongs to',
            'foreign_key' => [
                'table' => 'store',
                'column' => 'id',
                'name' => 'fk_testy_store',
                'on_delete' => 'CASCADE',
            ],
        ],
        'user_id' => [
            'db_type'   => 'foreignId',
            'nullable'  => false,
            'comment'   => 'User who created the record',
            'foreign_key' => [
                'table'     => 'user',
                'column'    => 'id',
                'name'      => 'fk_testy_user',
                'on_delete' => 'CASCADE',
            ],
        ],
        'super_powers' => [
            'db_type'   => 'array',
            'nullable'  => false,
            // 'default'   => [],
            'comment'   => 'JSON encoded array of user super_powers',
        ],
        'status' => [
            // 'db_type'   => 'char',
            'db_type'   => 'enum',
            // 'length'    => 1,
            // 'nullable'  => false,
            'default'   => 'A',
            'comment'   => 'P=Pending, A=Active, S=Suspended, B=Banned, D=Deleted',
            'check'     => "status IN ('J', 'P','A','S','B','D')", // Using CHECK constraint as per instructions
            // 'comment'   => 'P=Pending, A=Active, I=Inactive',
        ],
        'slug' => [
            'db_type'   => 'string',
            'length'    => 100,
            'nullable'  => false,
            'unique'    => true, // From migration
            'comment'   => 'Unique SEO-friendly slug for the testy',
        ],
        'title' => [
            'db_type' => 'string',
            'length'    => 255,
            'nullable'  => false,
            'comment'   => 'Title',
            'required'  => true,
            'minlength' => 5,
            'maxlength' => 50,
            // 'pattern'   => '[a-z0-9]/',
            // 'style'     => 'background: cyan;',
            // 'data-char-counter'    => true,
            // 'data-live-validation' => true,
        ],
        'generic_text' => [
            'db_type'   => 'string',
            'length'    => 60,
            'nullable'  => true,
            'comment'   => 'Generic text',
            'comment2'  => 'Generic short text',
            'required'  => true,
            'minlength' => 5,
            'maxlength' => 50,
        ],
        'content' => [
            'db_type'   => 'text',
            'nullable'  => true,
            'comment'   => 'Content',
            'comment2'  => 'Main content/body',
            'required'  => false,
            'minlength' => 5,
            'maxlength' => 5000,
        ],
        'image_count'   => [
            'db_type'   => 'integer',
            'nullable'  => true,
            'comment'   => 'Image Count',
        ],
        'cover_image_id' => [
            'db_type'   => 'bigInteger',
            'nullable'  => true,
            'unsigned'  => true,
            'comment'   => 'Cover image id',
            'comment2'  => 'Optional cover image id',
        ] ,
        'generic_code'  => [
            'db_type'   => 'string',
            'nullable'  => false,
            'comment'   => 'Generic Code',
        ],

        'date_of_birth' => [
            'db_type'   => 'date',
            'nullable'  => true,
            'comment'   => 'Date of Birth',
        ],
        'generic_date'  => [
            'db_type'   => 'date',
            'nullable'  => true,
            'comment'   => 'Generic Date',
        ],
        'generic_month' => [
            'db_type'   => 'string',
            'length'    => 50,
            'nullable'  => true,
            'comment'   => 'Generic Month',
        ],
        'generic_week'  => [
            'db_type'   => 'string',
            'length'    => 50,
            'nullable'  => true,
            'comment'   => 'Generic Week',
        ],
        'generic_time'  => [
            'db_type'   => 'time',
            'nullable'  => true,
            'comment'   => 'Generic Time',
        ],
        'generic_datetime' => [
            'db_type'   => 'dateTime',
            'nullable'  => true,
            'comment'   => 'Generic DateTime',
        ],
        'telephone'     => [
            'db_type'   => 'string',
            'length'    => 20,
            'nullable'  => true,
            'comment'   => 'Telephone number',
            'required'  => false,
            // 'minlength' => 1,
            'maxlength' => 20,
            'pattern'   => '[a-z0-9]/',
            'list'      => 'foo',
            'data-char-counter'     => true,     // js-feature
            'data-live-validation'  => true,      // js-feature
            'data-mask' => 'phone', // todo - mast does not validate.
                // 'xxdata-country'          => 'pt',    // todo - revisit for validation -  'pattern, maxlength
                // 'xxstyle' => 'background: cyan;',
        ],
        'gender_id' => [
            'db_type'   => 'string',
            'length'    => 4,
            'nullable'  => true,
            'comment'   => "Gender",
            'comment2'  => "Gender: m=Male, f=Female, o=Other, nb=Non-binary",
            'check'     => "gender_id IN ('m','f','o','nb')",
        ],
        'gender_other'  => [
            'db_type'   => 'string',
            'length'    => 50,
            'nullable'  => true,
            'comment'   => "Gender Other",
            'comment2'  => "If gender_id is 'o' (Other), specify here",
        ] ,
        'is_verified'   => [
            'db_type'   => 'boolean',
            'nullable'  => false,
            'default'   => false,
            'comment'   => 'Is Verified',
        ],
        'interest_soccer_ind' => [
            'db_type'   => 'boolean',
            'nullable'  => false,
            'default'   => false,
            'comment'   => 'Soccer Interest',
        ],
        'interest_baseball_ind' => [
            'db_type'   => 'boolean',
            'nullable'  => false,
            'default'   => false,
            'comment'   => 'Baseball Interest',
        ],
        'interest_football_ind' => [
            'db_type'   => 'boolean',
            'nullable'  => false,
            'default'   => false,
            'comment'   => 'Football Interest',
        ],
        'interest_hockey_ind' => [
            'db_type'   => 'boolean',
            'nullable'  => false,
            'default'   => false,
            'comment'   => 'Hockey Interest',
        ],
        'primary_email' => [
            'db_type'   => 'string',
            'length'    => 255,
            'nullable'  => true,
            'comment'   => 'Primary email',
            'required'  => true,
            'minlength' => 5,
            'maxlength' => 255,
        ],
        'secret_code_hash' => [
            'db_type'   => 'string',
            'length'    => 100,
            'nullable'  => true,
            'comment'   => 'Secret code hash',
        ],
        'balance' => [
            'db_type'   => 'decimal',
            'precision' => 10,
            'scale'     => 2,
            'nullable'  => false,
            'default'   => 0.00,
            'comment'   => 'Balance',
            'comment2'   => 'Account balance, max 100,000',
            'check'     => 'balance >= 0 AND balance <= 100000',
        ],
        'generic_decimal' => [
            'db_type'   => 'decimal',
            'precision' => 10,
            'scale'     => 5,
            'nullable'  => true,
            'comment'   => 'Generic Decimal',
        ],
        'volume_level'  => [
            'db_type'   => 'integer',
            'nullable'  => true,
            'unsigned'  => true,
            'comment'   => 'Volume Level',
        ],
        'start_rating' => [
            'db_type'   => 'decimal',
            'precision' => 7,
            'scale'     => 2,
            'nullable'  => true,
            'comment'   => 'Star Rating',
        ],
        'generic_number' => [
            'db_type'   => 'integer',
            'nullable'  => false,
            'default'   => 0,
            'comment'   => 'Generic Number',
        ],
        'generic_num' => [
            'db_type'   => 'integer',
            'nullable'  => false,
            'unsigned'  => true,
            'default'   => 55,
            'comment'   => 'Generic Number',
        ],
        'generic_color' => [
            'db_type'   => 'string',
            'length'    => 20,
            'nullable'  => true,
            'comment'   => 'Generic color',
        ],
        'wake_up_time'  => [
            'db_type'   => 'time',
            'nullable'  => true,
            'comment'   => 'Wake up time',
        ],
        'favorite_week_day' => [
            'db_type'   => 'string',
            'length'    => 10,
            'nullable'  => true,
            'comment'   => 'Favorite weekday',
        ],
        'online_address' => [
            'db_type'   => 'string',
            'length'    => 255,
            'nullable'  => true,
            'comment'   => 'Online address',
            'comment2'  => 'Online address or profile URL',
        ],
        'profile_picture' => [
            'db_type'   => 'string',
            'length'    => 255,
            'nullable'  => true,
            'comment'   => 'profile picture',
            'comment2'  => 'Path to uploaded profile picture',
        ],
        'created_at' => [
            'db_type'   => 'dateTime',
            'nullable'  => false,
            'comment'   => 'Created Date',
            'comment2'  => 'Timestamp when the record was created',
        ],
        'updated_at' => [
            'db_type'   => 'dateTime',
            'nullable'  => false,
            'comment'   => 'Last update',
            'comment2'  => 'Timestamp when the record was last updated',
        ]
    ],

    // Additional Indexes
    'indexes' => [
        [
            'name' => 'idx_status',
            'columns' => ['status'],
            'type' => 'index',
        ],
        [
            'name' => 'unique_slug_store',
            'columns' => ['slug', 'store_id'],
            'type' => 'unique',
        ],
    ],

    // Repository Configuration
    // 'repository' => [
        // 'extends' => 'AbstractMultiTenantRepository',
    // ],
    'repository' => [
        'extends' => 'AbstractMultiTenantRepository',
        'implements' => ['TestyRepositoryInterface', 'BaseRepositoryInterface'],
        'queries2' => [
            'findById' => "SELECT i.*, u.username
                FROM {tableName} i
                LEFT JOIN user u ON i.user_id = u.user_id
                WHERE i.{primaryKey} = :id",
            'findBy' => "SELECT i.*, u.username
                FROM {tableName} i
                LEFT JOIN user u ON i.user_id = u.user_id",
        ],
        'queries' => [
            'findById' => [
                'fromype' => 'LEFT',
                'type' => 'LEFT',
                'on' => 'i.user_id = u.user_id',
                'alias' => 'u',
                'select' => ['username'],
            ],
        ],
        'joins' => [
            'user' => [
                'type' => 'LEFT',
                'on' => 'i.user_id = u.user_id',
                'alias' => 'u',
                'select' => ['username'],
            ],
        ],
    ],

    // Controller Configuration
    'controller' => [
        'route_context' => 'account',
    ],
    /*
    'sample_data' => [
        [
            'store_id' => $storeId,
            'user_id' => $userId,
            'status' => 'P',
            'slug' => 'first-blog-testy',
            'title' => 'My First Blog Testy',
            'content' => 'This is the content of my first blog testy. Welcome to my blog!',
            'generic_text' => 'Hello',
            'date_of_birth' => '1990-01-01',
            'telephone' => '+1-555-123-4567',
            'gender_id' => 'm',
            'gender_other' => null,
            'is_verified' => true,
            'interest_soccer_ind' => true,
            'interest_baseball_ind' => false,
            'interest_football_ind' => true,
            'interest_hockey_ind' => false,
            'primary_email'       => 'alice@example.com',
            'secret_code_hash'         => 'X7F9-ALPHA-2025',
            'balance'             => 98765.43,
            'generic_decimal'     => 36.6,
            'generic_number'      => 2,
            'volume_level'        => 100,
            'start_rating'      => 3.2,
            'generic_color'          => 'Electric Blue',
            'wake_up_time'        => '05:45:00',
            'favorite_week_day'   => 'Friday',
            'online_address'      => 'https://aliceblog.example.com',
            'profile_picture'  => 'pictures/463280b37428348f.jpg',

            // --- NEW FIELDS ---
            // type="date" -> DATE (YYYY-MM-DD)
            'generic_date' => '1963-11-22',

            // type="month" -> VARCHAR(7) (YYYY-MM)
            'generic_month' => '1963-12',

            // type="week" -> VARCHAR(7) (YYYY-Www)
            'generic_week' => '1963-W52',

            // type="time" -> TIME (HH:MM:SS)
            'generic_time' => '15:30:00',

            // type="datetime-local" -> DATETIME (YYYY-MM-DD HH:MM:SS)
            'generic_datetime' => '1963-11-22 15:30:00',
            // ------------------
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s'),
        ],
        [
            'store_id' => $storeId,
            'user_id' => $userId,
            'status' => 'P',
            'slug' => 'learning-php',
            'title' => 'Learning PHP in 2025',
            'content' => 'PHP has evolved significantly over the years. ' .
                        'Here are some tips for learning PHP in 2025...',
            'generic_text' => 'Hello',
            'date_of_birth' => '1990-01-01',
            'telephone' => '+1-555-123-4567',
            'created_at' => date('Y-m-d H:i:s', strtotime('-1 day')),
            'updated_at' => date('Y-m-d H:i:s', strtotime('-1 day')),
        ],
        [
            'store_id' => $storeId,
            'user_id' => $userId,
            'status' => 'P',
            'slug' => 'mvc-architecture',
            'title' => 'Understanding MVC Architecture',
            'content' => 'Model-View-Controller (MVC) is a software design pattern commonly used for developing ' .
                        'user interfaces that divide the related program logic into three interconnected elements...',
            'generic_text' => 'Hello',
            'date_of_birth' => '1990-01-01',
            'telephone' => '+1-555-123-4567',
            'created_at' => date('Y-m-d H:i:s', strtotime('-2 days')),
            'updated_at' => date('Y-m-d H:i:s', strtotime('-2 days')),
        ],
        [
            'store_id' => $storeId,
            'user_id' => $userId,
            'status' => 'P',
            'slug' => 'database-migrations',
            'title' => 'The Power of Database Migrations',
            'content' => 'Database migrations provide a way to reliably update your database schema ' .
                        'and apply data changes...',
            'generic_text' => 'Hello',
            'date_of_birth' => '1990-01-01',
            'telephone' => '+1-555-123-4567',
            'created_at' => date('Y-m-d H:i:s', strtotime('-3 days')),
            'updated_at' => date('Y-m-d H:i:s', strtotime('-3 days')),
        ],
        [
            'store_id' => $storeId,
            'user_id' => $userId,
            'status' => 'P',
            'slug' => 'web-security',
            'title' => 'Web Security Best Practices',
            'content' => 'Security is critical for any web application. ' .
                        'Here are some best practices to keep your site secure...',
            'generic_text' => 'Hello',
            'date_of_birth' => '1990-01-01',
            'telephone' => '+1-555-123-4567',
            'created_at' => date('Y-m-d H:i:s', strtotime('-4 days')),
            'updated_at' => date('Y-m-d H:i:s', strtotime('-4 days')),
        ],
        [
            'store_id' => $storeId,
            'user_id' => $userId,
            'status' => 'P',
            'slug' => 'rest-api-design',
            'title' => 'REST API Design Guidelines 5',
            'content' => 'When designing a REST API, it\'s important to follow these principles...',
            'generic_text' => 'Hello',
            'date_of_birth' => '1990-01-01',
            'telephone' => '+1-555-123-4567',
            'created_at' => date('Y-m-d H:i:s', strtotime('-5 days')),
            'updated_at' => date('Y-m-d H:i:s', strtotime('-5 days')),
        ],
        [
            'store_id' => $storeId,
            'user_id' => $userId,
            'status' => 'D',
            'slug' => 'draft-testy',
            'title' => 'This is a Draft Testy',
            'content' => 'This testy is still being drafted and should not appear in the public listing.',
            'generic_text' => 'Hello',
            'date_of_birth' => '1990-01-01',
            'telephone' => '+1-555-123-4567',
            'created_at' => date('Y-m-d H:i:s', strtotime('-6 days')),
            'updated_at' => date('Y-m-d H:i:s', strtotime('-6 days')),
        ],
        [
            'store_id' => $storeId,
            'user_id' => $userId,
            'status' => 'P',
            'slug' => 'php-8-features',
            'title' => 'New Features in PHP 8',
            'content' => 'PHP 8 introduced several amazing features that every developer should know about...',
            'generic_text' => 'Hello',
            'date_of_birth' => '1990-01-01',
            'telephone' => '+1-555-123-4567',
            'created_at' => date('Y-m-d H:i:s', strtotime('-7 days')),
            'updated_at' => date('Y-m-d H:i:s', strtotime('-7 days')),
        ],
        [
            'store_id' => $storeId,
            'user_id' => $userId,
            'status' => 'P',
            'slug' => 'composer-best-practices',
            'title' => 'Composer Best Practices',
            'content' => 'Learn how to make the most of Composer for managing your PHP dependencies...',
            'generic_text' => 'Hello',
            'date_of_birth' => '1990-01-01',
            'telephone' => '+1-555-123-4567',
            'created_at' => date('Y-m-d H:i:s', strtotime('-8 days')),
            'updated_at' => date('Y-m-d H:i:s', strtotime('-8 days')),
        ],
        [
            'store_id' => $storeId,
            'user_id' => $userId,
            'status' => 'P',
            'slug' => 'dependency-injection',
            'title' => 'Understanding Dependency Injection',
            'content' => 'Dependency Injection is a design pattern that implements Inversion of Control ' .
                        'for resolving dependencies...',
            'generic_text' => 'Hello',
            'date_of_birth' => '1990-01-01',
            'telephone' => '+1-555-123-4567',
            'created_at' => date('Y-m-d H:i:s', strtotime('-9 days')),
            'updated_at' => date('Y-m-d H:i:s', strtotime('-9 days')),
        ],
        [
            'store_id' => $storeId,
            'user_id' => $userId,
            'status' => 'P',
            'slug' => 'first-blog-testy2',
            'title' => 'My First Blog Testy 10',
            'content' => 'This is the content of my first blog testy. Welcome to my blog!',
            'generic_text' => 'Hello',
            'date_of_birth' => '1990-01-01',
            'telephone' => '+1-555-123-4567',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s'),
        ],
        [
            'store_id' => $storeId,
            'user_id' => $userId,
            'status' => 'P',
            'slug' => 'learning-php2',
            'title' => 'Learning PHP in 2025',
            'content' => 'PHP has evolved significantly over the years. ' .
                        'Here are some tips for learning PHP in 2025...',
            'generic_text' => 'Hello',
            'date_of_birth' => '1990-01-01',
            'telephone' => '+1-555-123-4567',
            'created_at' => date('Y-m-d H:i:s', strtotime('-1 day')),
            'updated_at' => date('Y-m-d H:i:s', strtotime('-1 day')),
        ],
        [
            'store_id' => $storeId,
            'user_id' => $userId,
            'status' => 'P',
            'slug' => 'mvc-architecture2',
            'title' => 'Understanding MVC Architectu13',
            'content' => 'Model-View-Controller (MVC) is a software design pattern commonly used for developing ' .
                        'user interfaces that divide the related program logic into three interconnected elements...',
            'generic_text' => 'Hello',
            'date_of_birth' => '1990-01-01',
            'telephone' => '+1-555-123-4567',

            'gender_id'           => 'm',
            'gender_other'        => null,
            'is_verified'         => true,
            'interest_soccer_ind' => true,
            'interest_baseball_ind' => false,
            'interest_football_ind' => true,
            'interest_hockey_ind'   => false,

            'primary_email'       => 'alice@example.com',
            'secret_code_hash'         => 'X7F9-ALPHA-2025',
            'balance'             => 98765.43,
            'generic_decimal'       => 36.6,
            'generic_number'        => 2,
            'volume_level'          => 100,
            'start_rating'          => 3.2,
            'generic_color'          => 'Electric Blue',
            'wake_up_time'        => '05:45:00',
            'favorite_week_day'   => 'Friday',
            'online_address'      => 'https://aliceblog.example.com',

            'generic_date'      => '1963-11-22',
            'generic_month'     => '1963-12',
            'generic_week'      => '1963-W52',
            'generic_time'      => '15:30:00',
            'generic_datetime'  => '1963-11-22 15:30:00',
            'profile_picture'  => 'pictures/463280b37428348f.jpg',

            'created_at' => date('Y-m-d H:i:s', strtotime('-2 days')),
            'updated_at' => date('Y-m-d H:i:s', strtotime('-2 days')),
        ],
        [
            'store_id' => $storeId,
            'user_id' => $userId,
            'status' => 'P',
            'slug' => 'database-migrations2',
            'title' => 'The Power of Database Migrations',
            'content' => 'Database migrations provide a way to reliably update your database schema ' .
                        'and apply data changes...',
            'generic_text' => 'Hello',
            'date_of_birth' => '1990-01-01',
            'telephone' => '+1-555-123-4567',

            'gender_id'           => 'm',
            'gender_other'        => null,
            'is_verified'         => true,
            'interest_soccer_ind' => true,
            'interest_baseball_ind' => false,
            'interest_football_ind' => true,
            'interest_hockey_ind'   => false,

            'primary_email'       => 'alice@example.com',
            'secret_code_hash'         => 'X7F9-ALPHA-2025',
            'balance'             => 98765.43,
            'generic_decimal'         => 36.6,
            'generic_number'      => 2,
            'volume_level'        => 100,
            'start_rating'        => 3.2,
            'generic_color'       => 'Electric Blue',
            'wake_up_time'        => '05:45:00',
            'favorite_week_day'   => 'Friday',
            'online_address'      => 'https://aliceblog.example.com',

            'generic_date' => '1963-11-22',
            'generic_month' => '1963-12',
            'generic_week' => '1963-W52',
            'generic_time' => '15:30:00',
            'generic_datetime' => '1963-11-22 15:30:00',

            'created_at' => date('Y-m-d H:i:s', strtotime('-3 days')),
            'updated_at' => date('Y-m-d H:i:s', strtotime('-3 days')),
        ],
        [
            'store_id' => $storeId,
            'user_id' => $userId,
            'status' => 'P',
            'slug' => 'web-security2',
            'title' => 'Web Security Best Practices',
            'content' => 'Security is critical for any web application. ' .
                        'Here are some best practices to keep your site secure...',
            'generic_text' => 'Hello',
            'date_of_birth' => '1990-01-01',
            'telephone' => '+1-555-123-4567',
            'created_at' => date('Y-m-d H:i:s', strtotime('-4 days')),
            'updated_at' => date('Y-m-d H:i:s', strtotime('-4 days')),
        ],
        [
            'store_id' => $storeId,
            'user_id' => $userId,
            'status' => 'P',
            'slug' => 'rest-api-design2',
            'title' => 'REST API Design Guidelines',
            'content' => 'When designing a REST API, it\'s important to follow these principles...',
            'generic_text' => 'Hello',
            'date_of_birth' => '1990-01-01',
            'telephone' => '+1-555-123-4567',
            'created_at' => date('Y-m-d H:i:s', strtotime('-5 days')),
            'updated_at' => date('Y-m-d H:i:s', strtotime('-5 days')),
        ],
        [
            'store_id' => $storeId,
            'user_id' => $userId,
            'status' => 'D',
            'slug' => 'draft-testy2',
            'title' => 'This is a Draft Testy',
            'content' => 'This testy is still being drafted and should not appear in the public listing.',
            'generic_text' => 'Hello',
            'date_of_birth' => '1990-01-01',
            'telephone' => '+1-555-123-4567',
            'created_at' => date('Y-m-d H:i:s', strtotime('-6 days')),
            'updated_at' => date('Y-m-d H:i:s', strtotime('-6 days')),
        ],
        [
            'store_id' => $storeId,
            'user_id' => $userId,
            'status' => 'P',
            'slug' => 'php-8-features2',
            'title' => 'New Features in PHP 8',
            'content' => 'PHP 8 introduced several amazing features that every developer should know about...',
            'generic_text' => 'Hello',
            'date_of_birth' => '1990-01-01',
            'telephone' => '+1-555-123-4567',
            'created_at' => date('Y-m-d H:i:s', strtotime('-7 days')),
            'updated_at' => date('Y-m-d H:i:s', strtotime('-7 days')),
        ],
        [
            'store_id' => $storeId,
            'user_id' => $userId,
            'status' => 'P',
            'slug' => 'composer-best-practices2',
            'title' => 'Composer Best Practices',
            'content' => 'Learn how to make the most of Composer for managing your PHP dependencies...',
            'generic_text' => 'Hello',
            'date_of_birth' => '1990-01-01',
            'telephone' => '+1-555-123-4567',
            'created_at' => date('Y-m-d H:i:s', strtotime('-8 days')),
            'updated_at' => date('Y-m-d H:i:s', strtotime('-8 days')),
        ],
        [
            'store_id' => $storeId,
            'user_id' => $userId,
            'status' => 'P',
            'slug' => 'dependency-injection2',
            'title' => 'Understanding Dependency Injection',
            'content' => 'Dependency Injection is a design pattern that implements Inversion of Control ' .
                        'for resolving dependencies...',
            'generic_text' => 'Hello',
            'date_of_birth' => '1990-01-01',
            'telephone' => '+1-555-123-4567',
            'created_at' => date('Y-m-d H:i:s', strtotime('-9 days')),
            'updated_at' => date('Y-m-d H:i:s', strtotime('-9 days')),
        ],
    ],
    */
];
